#!/bin/bash
# Source app helpers
source /usr/share/yunohost/helpers
source .fonctions
set -eu

# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
is_public=$YNH_APP_ARG_IS_PUBLIC

app=$YNH_APP_INSTANCE_NAME

# Source app helpers
source /usr/share/yunohost/helpers

script_dir=$PWD

# Vérifie que les variables ne sont pas vides.
CHECK_VAR "$app" "app name not set"
CHECK_VAR "$script_dir" "script_dir not set"

CHECK_PATH	# Vérifie et corrige la syntaxe du path.
CHECK_DOMAINPATH	# Vérifie la disponibilité du path et du domaine.

CHECK_FINALPATH	# Vérifie que le dossier de destination n'est pas déjà utilisé.

# Install dependency to convert tracks to a readable format for the browser
sudo cp -a ../conf/umap.list /etc/apt/sources.list.d/
sudo apt-get update
sudo apt-get -t stretch -y install python3.5 python3.5-dev python-virtualenv uwsgi uwsgi-plugin-python3 postgresql-9.4 postgresql-9.4-postgis-2.2 postgresql-server-dev-9.4 libpq-dev

# Prepare Umap to be installed
sudo mkdir -p /srv/$app
sudo useradd -N umap -d /srv/$app/

# Setting up the database
dbname=$app
dbuser=$app

# Generate random password
dbpass=$(ynh_string_random)
##### dbpass
ynh_psql_create_db "$dbname" "$dbuser" "$dbpass"
sudo su -c "psql" postgres <<< \
        "CREATE EXTENSION postgis;"
        
sudo chown umap /srv/$app -R
sudo chmod 755 /srv/$app -R 
        
# Installation de "umap"
sudo su -c "virtualenv /srv/$app/venv" $app
sudo pip install $app-project
sudo su -c "wget https://raw.githubusercontent.com/umap-project/umap/master/umap/settings/local.py.sample -O /srv/$app/local.py" $app
sudo su -c "export UMAP_SETTINGS=/srv/$app/local.py" $app
sudo su -c "umap migrate" $app
sudo su -c "umap collectstatic" $app
sudo su -c "umap storagei18n" $app
sudo su -c "umap createsuperuser" $app  

# PWD
cd $script_dir
# Copy Files
sudo cp ./config/uwsgi_params /srv/$app/uwsgi_params
sudo cp ./config/uwsgi.ini /srv/$app/uwsgi.ini

# Config service
sudo ln -s /srv/$app/uwsgi.ini /etc/uwsgi/apps-enabled/umap.ini
sudo systemctl restart uwsgi nginx

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
nginxconf=/etc/nginx/conf.d/$domain.d/$app.conf
sudo cp ../conf/nginx.conf $nginxconf
sudo chown root: $nginxconf
sudo chmod 600 $nginxconf

ynh_app_setting_set "$app" is_public "$is_public"
if [ "$is_public" = "Yes" ];
then
  ynh_app_setting_set "$app" unprotected_uris "/"
fi

sudo service nginx reload
sudo yunohost app ssowatconf



