#!/bin/bash

source .fonctions
set -eu

# Retrieve arguments
domain=$1
path=$2
is_public=$3

app=$YNH_APP_INSTANCE_NAME

# Source app helpers
source /usr/share/yunohost/helpers

script_dir=$PWD

# Vérifie que les variables ne sont pas vides.
CHECK_VAR "$app" "app name not set"
CHECK_VAR "$script_dir" "script_dir not set"

CHECK_PATH	# Vérifie et corrige la syntaxe du path.
CHECK_DOMAINPATH	# Vérifie la disponibilité du path et du domaine.

CHECK_FINALPATH	# Vérifie que le dossier de destination n'est pas déjà utilisé.

# Install dependency to convert tracks to a readable format for the browser
sudo apt-get update
sudo apt install python3.5 python3.5-dev python-virtualenv uwsgi uwsgi-plugin-python3 postgresql-9.5 postgresql-9.5-postgis-2.2 git

sudo mkdir -p /srv/$app

sudo useradd -N umap -d /srv/$app/

sudo -u postgres createuser $app
sudo -u postgres createdb umap -O $app
sudo -u postgres psql $app -c "CREATE EXTENSION postgis"

sudo -u $app -i
virtualenv /srv/$app/venv --python=/usr/bin/python3.5
source /srv/umap/venv/bin/activate
pip install $app-project
wget https://raw.githubusercontent.com/umap-project/umap/master/umap/settings/local.py.sample -O /srv/$app/local.py
export UMAP_SETTINGS=/srv/$app/local.py
umap migrate
umap collectstatic
umap storagei18n
umap createsuperuser

# Copy Files
sudo cp ./config/uwsgi_params /srv/$app/uwsgi_params
sudo cp ./config/uwsgi.ini /srv/$app/uwsgi.ini

# Config service
sudo ln -s /srv/$app/uwsgi.ini /etc/uwsgi/apps-enabled/umap.ini
sudo systemctl restart uwsgi nginx



